# Generated by Django 6.0.6 on 2026-08-10 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('vin', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('kilometraje_actual', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vehiculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Complejidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('factor_precio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tiempo_extra_minutos', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'complejidad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'componente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_actual', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'producto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'rol',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_mano_obra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiempo_estimado_minutos', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'servicio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_servicio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NotaPredefinida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20)),
                ('texto', models.CharField(max_length=200)),
                ('id_componente', models.ForeignKey(db_column='id_componente', on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_vehicular.componente')),
            ],
            options={
                'db_table': 'nota_predefinida',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('estado_orden', models.CharField(blank=True, max_length=30, null=True)),
                ('observacion_general', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('id_complejidad', models.ForeignKey(blank=True, db_column='id_complejidad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_vehicular.complejidad')),
                ('id_vehiculo', models.ForeignKey(db_column='id_vehiculo', on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_vehicular.vehiculo')),
                ('id_servicio', models.ForeignKey(blank=True, db_column='id_servicio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_vehicular.servicio')),
                ('id_tipo_servicio', models.ForeignKey(blank=True, db_column='id_tipo_servicio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_vehicular.tiposervicio')),
            ],
            options={
                'db_table': 'orden_trabajo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RevisionTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_revision', models.CharField(max_length=30)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('isv_porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('id_orden', models.ForeignKey(db_column='id_orden', on_delete=django.db.models.deletion.DO_NOTHING, related_name='revisiones', to='gestion_vehicular.ordentrabajo')),
            ],
            options={
                'db_table': 'revision_tecnica',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20)),
                ('nota', models.TextField(blank=True, null=True)),
                ('foto_ruta', models.TextField(blank=True, null=True)),
                ('id_componente', models.ForeignKey(db_column='id_componente', on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_vehicular.componente')),
                ('id_revision', models.ForeignKey(db_column='id_revision', on_delete=django.db.models.deletion.DO_NOTHING, related_name='detalles', to='gestion_vehicular.revisiontecnica')),
            ],
            options={
                'db_table': 'detalle_revision',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='servicio',
            name='id_tipo_servicio',
            field=models.ForeignKey(blank=True, db_column='id_tipo_servicio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_vehicular.tiposervicio'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('ci', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('usuario_login', models.CharField(max_length=50, unique=True)),
                ('contrasena_hash', models.CharField(max_length=255)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_vehicular.rol')),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='revisiontecnica',
            name='id_mecanico',
            field=models.ForeignKey(blank=True, db_column='id_mecanico', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_vehicular.usuario'),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total_servicios', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_total_productos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_pago', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('comprobante', models.CharField(blank=True, max_length=100, null=True)),
                ('id_orden', models.ForeignKey(db_column='id_orden', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pago', to='gestion_vehicular.ordentrabajo')),
                ('cobrado_por', models.ForeignKey(blank=True, db_column='cobrado_por', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_vehicular.usuario')),
            ],
            options={
                'db_table': 'pago',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='creado_por',
            field=models.ForeignKey(blank=True, db_column='creado_por', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordenes_creadas', to='gestion_vehicular.usuario'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='id_jefe_tecnico',
            field=models.ForeignKey(blank=True, db_column='id_jefe_tecnico', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordenes_supervisadas', to='gestion_vehicular.usuario'),
        ),
        migrations.CreateModel(
            name='NotaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=30)),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.TextField()),
                ('visible_en_proxima', models.BooleanField(blank=True, null=True)),
                ('id_vehiculo', models.ForeignKey(db_column='id_vehiculo', on_delete=django.db.models.deletion.DO_NOTHING, related_name='notas_tecnicas', to='gestion_vehicular.vehiculo')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_vehicular.usuario')),
            ],
            options={
                'db_table': 'nota_tecnica',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=30, null=True)),
                ('estado_nuevo', models.CharField(max_length=30)),
                ('fecha_cambio', models.DateTimeField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('id_orden', models.ForeignKey(db_column='id_orden', on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_vehicular.ordentrabajo')),
                ('cambiado_por', models.ForeignKey(blank=True, db_column='cambiado_por', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_vehicular.usuario')),
            ],
            options={
                'db_table': 'historial_estado_orden',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HallazgoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado_autorizacion', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_deteccion', models.DateTimeField(blank=True, null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('foto_ruta', models.TextField(blank=True, null=True)),
                ('id_orden', models.ForeignKey(db_column='id_orden', on_delete=django.db.models.deletion.DO_NOTHING, related_name='hallazgos', to='gestion_vehicular.ordentrabajo')),
                ('id_mecanico', models.ForeignKey(blank=True, db_column='id_mecanico', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_vehicular.usuario')),
                ('resuelto_por', models.ForeignKey(blank=True, db_column='resuelto_por', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hallazgos_resueltos', to='gestion_vehicular.usuario')),
            ],
            options={
                'db_table': 'hallazgo_adicional',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_cobrado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costo_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('id_orden', models.ForeignKey(db_column='id_orden', on_delete=django.db.models.deletion.DO_NOTHING, related_name='detalles_servicio', to='gestion_vehicular.ordentrabajo')),
                ('id_servicio', models.ForeignKey(db_column='id_servicio', on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_vehicular.servicio')),
                ('id_mecanico', models.ForeignKey(blank=True, db_column='id_mecanico', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_vehicular.usuario')),
            ],
            options={
                'db_table': 'detalle_servicio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subtotal_precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_orden', models.ForeignKey(db_column='id_orden', on_delete=django.db.models.deletion.DO_NOTHING, related_name='detalles_producto', to='gestion_vehicular.ordentrabajo')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_vehicular.producto')),
                ('registrado_por', models.ForeignKey(blank=True, db_column='registrado_por', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_vehicular.usuario')),
            ],
            options={
                'db_table': 'detalle_producto',
                'managed': True,
            },
        ),
    ]
