# Generated by Django 6.0.6 on 2026-08-09 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_vehicular', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hallazgoadicional',
            options={'managed': True},
        ),
    ]
